---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install required packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-11-jdk
    - maven
    - wget
    - unzip

- name: Add Jenkins GPG key
  become: true
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  become: true
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: jenkins

- name: Update apt cache after adding Jenkins repository
  become: true
  apt:
    update_cache: yes

- name: Install Jenkins
  become: true
  apt:
    name: jenkins
    state: present
